name: Continues Integration

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '17', '19']
        os: [ ubuntu-latest, windows-latest ]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.java }}-${{ matrix.os }}-${{ github.run_number }}
          release_name: ${{ matrix.java }}-${{ matrix.os }}-${{ github.run_number }}
