name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    strategy:
      matrix:
        java: [ '19' ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    name: Java ${{ matrix.java }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew buildPlugin
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ij-textmate-plugin-${{ matrix.os }}-java-${{ matrix.java }}-${{ github.ref_name }}
          release_name: ij-textmate-plugin-${{ matrix.os }}-java-${{ matrix.java }}-${{ github.ref_name }}

      - name: Upload Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/libs/*.jar"
          tag_name: ij-textmate-plugin-${{ matrix.os }}-java-${{ matrix.java }}-${{ github.ref_name }}
          draft: false
